### ISSUE TITLE
Cannot read property 'cssRules' of undefined

### ISSUE THREAD

**Issue by luiscarli** [threepointone/react-css#10]
Hi the idea of this lib is really great! I want to start using it instead of Radium.

I'm having trouble running the code, I'm getting 'Cannot read property 'cssRules' of undefined' on the following line: `insertSheetRule(cssrule(type, style, id), sheet.cssRules.length);`

I'm doing a simple test:
```
import {style} from '@threepointone/react-css'

export default class Test extends React.Component {
  render() {
    return <div
        {...style({ color: 'red', cursor: 'pointer' })}
      >
        TEST
      </div>
  }
}
```

**Comment by threepointone** [comment]
Damn, will fix. What browser/is are you on?

**Comment by luiscarli** [comment]
Last MacOS and last Chrome. It could be something related to my build setup. 
I will try again with a clean react-create-app to try to narrow the problem.

**Comment by threepointone** [comment]
I'm setting up my browserstack infra tonight, will see what it turns up.

**Comment by threepointone** [comment]
Tell me about your build setup, do you have rollup or something in it?

**Comment by threepointone** [comment]
Any updates? I'm rewritten a lot, might have resolved your issue.

**Comment by threepointone** [comment]
Closing this, please reopen if you can reproduce. Thanks!

**Comment by luiscarli** [comment]
It's working now! I'm very excited with this lib.
Thanks!

**Comment by threepointone** [comment]
Awesome! Lemme know how it goes, happy for suggestions
